In [ ]:
Numpy >> Numerical python

# Application >>

In [ ]:
1. Linear Algebra
2. Statistics
3. Trigonomerty
4. Matrix Operations
5. Image procesing
6. Logarithmic

# Numpy Properties

In [ ]:
1. It is a collection of homogenous datatype
2. Numpy is faster than list
3. Numpy is written in C and C++ language (Partially in python)
4. C language is faster than python

Data type >> numpy.ndarray >> n-Dimensional array

In [5]:
list1 = [1,2,34,"python",5.3]
print(list1)
print(type(list1))

[1, 2, 34, 'python', 5.3]
<class 'list'>


In [4]:
import numpy as np

array1 = np.array([2,4,5,6])
array1

array([2, 4, 5, 6])

In [6]:
print(type(array1))

<class 'numpy.ndarray'>


In [7]:
array1 = np.array([2,3,4,5,6])
array1

array([2, 3, 4, 5, 6])

In [8]:
array1 = np.array([2,3,4,5,6.5])
array1

array([2. , 3. , 4. , 5. , 6.5])

In [9]:
array1 = np.array([2,3,4,5,"6"])
array1

array(['2', '3', '4', '5', '6'], dtype='<U11')

In [10]:
array1 = np.array([2,3,4,5,4+5j])
array1

array([2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 4.+5.j])

# type casting in Numpy array

In [11]:
array1 = np.array([2,3,4,5,6.5],dtype = "int")
array1

array([2, 3, 4, 5, 6])

In [12]:
array1 = np.array([2,3,4,5,6.5],dtype = "float")
array1

array([2. , 3. , 4. , 5. , 6.5])

In [13]:
array1 = np.array([2,3,4,5,6.5],dtype = "f")
array1

array([2. , 3. , 4. , 5. , 6.5], dtype=float32)

In [14]:
array1 = np.array([2,3,4,5,6.5],dtype = complex)
array1

array([2. +0.j, 3. +0.j, 4. +0.j, 5. +0.j, 6.5+0.j])

In [15]:
array1 = np.array([2,3,4,5,6+5j],dtype = float)
array1

TypeError: can't convert complex to float

In [16]:
array1 = np.array([2,3,4,5,6+5j],dtype = int)
array1

TypeError: can't convert complex to int

In [17]:
array1 = np.array([2,3,4,5,6],dtype = str)
array1

array(['2', '3', '4', '5', '6'], dtype='<U1')

In [18]:
array1 = np.array((2,3,4,5,6))
array1

array([2, 3, 4, 5, 6])

# Dimension in Numpy array

# 1. 0-D array

In [19]:
array0 = np.array(30)
array0

array(30)

In [20]:
array0 = np.array(300)
array0

array(300)

In [21]:
array0 = np.array(300)
array0.ndim

0

In [22]:
array0 = np.array(300)
print("Number of dimension of an array :",array0.ndim)

Number of dimension of an array : 0


## 2. 1-Dimensional array

In [ ]:
IT IS COLLECTION OF MULTIPLE 0-dimensional arrays

In [23]:
array1 = np.array([2,3,4,5,6])
print("array is :",array1)
print("Number of dimension of an array :",array1.ndim)

array is : [2 3 4 5 6]
Number of dimension of an array : 1


In [24]:
array1 = np.array([2])
print("array is :",array1)
print("Number of dimension of an array :",array1.ndim)

array is : [2]
Number of dimension of an array : 1


In [25]:
array1 = np.array((2))  # np.array(2)
print("array is :",array1)
print("Number of dimension of an array :",array1.ndim)

array is : 2
Number of dimension of an array : 0


In [27]:
a = (2)
print(a,type(a))

2 <class 'int'>


In [28]:
a = (2,)
print(a,type(a))

(2,) <class 'tuple'>


In [29]:
array1 = np.array((2,))  
print("array is :",array1)
print("Number of dimension of an array :",array1.ndim)

array is : [2]
Number of dimension of an array : 1


## 3. 2-Dimensional array

In [ ]:
It is collection of multiple 1 -dimensional arrays

In [31]:
array2 = np.array([[2,3,4],[10,20,30]])
print("array is :\n",array2)
print("Number of dimension of an array :",array2.ndim)

array is :
 [[ 2  3  4]
 [10 20 30]]
Number of dimension of an array : 2


In [32]:
array2 = np.array([[2,3,4],[10,20,30],[100,200,300]])
print("array is :\n",array2)
print("Number of dimension of an array :",array2.ndim)

array is :
 [[  2   3   4]
 [ 10  20  30]
 [100 200 300]]
Number of dimension of an array : 2


In [33]:
array2 = np.array([[2,3,4],[10,20,30],[100,200]])
print("array is :\n",array2)
print("Number of dimension of an array :",array2.ndim)

array is :
 [list([2, 3, 4]) list([10, 20, 30]) list([100, 200])]
Number of dimension of an array : 1


<ipython-input-33-3d3e37fd59ba>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array2 = np.array([[2,3,4],[10,20,30],[100,200]])


In [34]:
l1 = [[2,3,4],[10,20,30],[100,200,300]]
l1

[[2, 3, 4], [10, 20, 30], [100, 200, 300]]

In [35]:
l1 = [[2,3,4],[10,20,30],[100,200]]
l1

[[2, 3, 4], [10, 20, 30], [100, 200]]

In [36]:
l1 = [[2,3,4],[10,20,30],[100,200],300]
l1

[[2, 3, 4], [10, 20, 30], [100, 200], 300]

# 4.3-D array

In [ ]:
It is collection of multiple 2 dimentional arrays

In [37]:
array3 = np.array([[[2,3,4],[10,20,30],[100,200,300]]])
print("array is :\n",array3)
print("Number of dimension of an array :",array3.ndim)

array is :
 [[[  2   3   4]
  [ 10  20  30]
  [100 200 300]]]
Number of dimension of an array : 3


In [39]:
array3 = np.array([[[2,3,4],[10,20,30],[100,200,300],[1,2,3]]])
print("array is :\n",array3)
print("Number of dimension of an array :",array3.ndim)

array is :
 [[[  2   3   4]
  [ 10  20  30]
  [100 200 300]
  [  1   2   3]]]
Number of dimension of an array : 3


# Access items using indexing and slicing

In [40]:
list1 = [3,4,5,6,7]
list1[3]

6

In [41]:
list1 = [3,4,5,6,7]
list1[1:3]

[4, 5]

In [42]:
array1 = np.array([3,4,5,6,7])
array1[3]

6

In [44]:
array1 = np.array([3,4,5,6,7])
array1[4]

7

In [46]:
array1 = np.array([3,4,5,6,7])
array1[4]

array([4, 5, 6])

In [47]:
array1 = np.array([3,4,5,6,7])
array1[-3:-1]

array([5, 6])

In [48]:
array1 = np.array([3,4,5,6,7])
array1[-3:]

array([5, 6, 7])

In [49]:
array1 = np.array([3,4,5,6,7])
array1[-3]

5

In [50]:
array1 = np.array([3,4,5,6,7])
array1[::-1]

array([7, 6, 5, 4, 3])

In [53]:
array1 = np.array([3,4,5,6,7])
array1[1:4:1]

array([4, 5, 6])

In [54]:
array1 = np.array([3,4,5,6,7])
array1[1:4:2]

array([4, 6])

In [55]:
array1 = np.array([3,4,5,6,7])
array1[4:1]

array([], dtype=int32)

In [56]:
array1 = np.array([3,4,5,6,7])
array1[4:1:-1]

array([7, 6, 5])

In [57]:
array1 = np.array([3,4,5,6,7])
array1[4:1:-2]

array([7, 5])

In [58]:
array2 = np.array([[2,3,4],[10,20,30],[40,50,60]])
array2

array([[ 2,  3,  4],
       [10, 20, 30],
       [40, 50, 60]])

In [59]:
array2[1]

array([10, 20, 30])

In [60]:
array2[1][2]

30

In [61]:
array2[1,2]

30

In [63]:
array2[2][0]

40

In [64]:
array2[2,0]

40

In [65]:
array2

array([[ 2,  3,  4],
       [10, 20, 30],
       [40, 50, 60]])

In [66]:
array2[2,1]

50

In [67]:
array2[:,:]  # all rows and all column

array([[ 2,  3,  4],
       [10, 20, 30],
       [40, 50, 60]])

In [68]:
array2[:,1]# all rows and 1st column

array([ 3, 20, 50])

In [69]:
array2[1,:] # 1st  row and all column

array([10, 20, 30])

In [70]:
array2[1,:2]# 1st index row, and (:2) >> 0 and 1 st column

array([10, 20])

In [71]:
array2[:,2]

array([ 4, 30, 60])

In [72]:
array2[:,0]

array([ 2, 10, 40])

In [73]:
array2[:,:]  

array([[ 2,  3,  4],
       [10, 20, 30],
       [40, 50, 60]])

In [74]:
array2[1:,:]

array([[10, 20, 30],
       [40, 50, 60]])

In [75]:
array2[1:,:2]

array([[10, 20],
       [40, 50]])

# HomeWork

In [91]:
array1 = np.array([[2,3,4],[5,6,7],[10,20,30]])
print(array1)

[[ 2  3  4]
 [ 5  6  7]
 [10 20 30]]


In [ ]:
array1[1:,1:]

In [ ]:
array3 = np.array([[[2,3,4],[5,6,7],[1,6,9],[10,60,90]],[[21,31,41],[51,61,71],[10,20,30],[100,200,300]]])
array3

In [ ]:
array3[1]

In [ ]:
array3[1,0]

In [ ]:
array3[1,0,2]

In [ ]:
array3[:,:,1]

In [ ]:
array3[:,2:,1:]

In [ ]:
array3[:,2:,0:2]

# Numpy Functions

# 1. Shape

In [76]:
array1 = np.array([2,3,4,5,6,7,10,20,30,50,60,70])
len(array1)

12

In [77]:
array1 = np.array([2,3,4,5,6,7,10,20,30,50,60,70])
array1.shape

(12,)

In [78]:
array1 = np.array([[2,3,4],[5,6,7],[10,20,30]])
array1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [10, 20, 30]])

In [79]:
array1.shape

(3, 3)

In [80]:
array3 = np.array([[[2,3,4],[5,6,7],[1,6,9],[10,20,30]],[[21,31,41],[51,61,71],[10,60,90],[100,200,300]]])
array3

array([[[  2,   3,   4],
        [  5,   6,   7],
        [  1,   6,   9],
        [ 10,  20,  30]],

       [[ 21,  31,  41],
        [ 51,  61,  71],
        [ 10,  60,  90],
        [100, 200, 300]]])

In [81]:
array3.shape

(2, 4, 3)

In [82]:
array3 = np.array([[[2,3,4],[5,6,7],[1,6,9],[10,20,30]],[[21,31,41],[51,61,71],[10,60,90],[100,200,300]]])
print("array3 is :",array3)
print("Number of dimension:", array3.ndim)

array3 is : [[[  2   3   4]
  [  5   6   7]
  [  1   6   9]
  [ 10  20  30]]

 [[ 21  31  41]
  [ 51  61  71]
  [ 10  60  90]
  [100 200 300]]]
Number of dimension: 3


In [83]:
array3 = np.array([[[2,3,4],[5,6,7],[1,6,9],[10,20,30]],[[21,31,41],[51,61,71],[10,60,90],[100,200,300]]])
print("array3 is :",array3)
print("Number of dimension:", array3.ndim)
print("Shape of given array:",array3.shape)

array3 is : [[[  2   3   4]
  [  5   6   7]
  [  1   6   9]
  [ 10  20  30]]

 [[ 21  31  41]
  [ 51  61  71]
  [ 10  60  90]
  [100 200 300]]]
Number of dimension: 3
Shape of given array: (2, 4, 3)


In [86]:
array1 = np.array([2,3,4,5,6,7,10,20,30,50,60,70],ndmin = 2)
print(array1)
print("Dimension od array is :",array1.ndim)

[[ 2  3  4  5  6  7 10 20 30 50 60 70]]
Dimension od array is : 2


In [87]:
array1 = np.array([2,3,4,5,6,7,10,20,30,50,60,70],ndmin = 3)
print(array1)
print("Dimension od array is :",array1.ndim)

[[[ 2  3  4  5  6  7 10 20 30 50 60 70]]]
Dimension od array is : 3


In [88]:
array1 = np.array([[2,3,4],[5,6,7],[10,20,30]],ndmin = 2)
print("array1 is :\n",array1)
print("Dimension od array is :",array1.ndim)
print("Shape of given array:",array1.shape)

array1 is :
 [[ 2  3  4]
 [ 5  6  7]
 [10 20 30]]
Dimension od array is : 2
Shape of given array: (3, 3)


In [89]:
array1 = np.array([[2,3,4],[5,6,7],[10,20,30]],ndmin = 3)
print("array1 is :\n",array1)
print("Dimension od array is :",array1.ndim)
print("Shape of given array:",array1.shape)

array1 is :
 [[[ 2  3  4]
  [ 5  6  7]
  [10 20 30]]]
Dimension od array is : 3
Shape of given array: (1, 3, 3)


In [90]:
array1 = np.array([[2,3,4],[5,6,7],[10,20,30]],ndmin = 6)
print("array1 is :\n",array1)
print("Dimension od array is :",array1.ndim)
print("Shape of given array:",array1.shape)

array1 is :
 [[[[[[ 2  3  4]
     [ 5  6  7]
     [10 20 30]]]]]]
Dimension od array is : 6
Shape of given array: (1, 1, 1, 1, 3, 3)
